"""Generate standalone Bash completion from the CLI's parser tree."""

from __future__ import annotations

import argparse
import shlex


def bash_completion(parser: argparse.ArgumentParser) -> str:
    transitions: list[str] = []
    suggestions: list[str] = []
    value_options: set[str] = set()

    def visit(current: argparse.ArgumentParser, state: str) -> None:
        words: list[str] = []
        for action in current._actions:
            words.extend(action.option_strings)
            if action.option_strings and action.nargs != 0:
                value_options.update(action.option_strings)
            if isinstance(action, argparse._SubParsersAction):
                for name, child in action.choices.items():
                    words.append(name)
                    target = f"{state}/{name}"
                    transitions.append(
                        f"            {shlex.quote(state + ':' + name)}) "
                        f"state={shlex.quote(target)} ;;"
                    )
                    visit(child, target)
            elif not action.option_strings and action.choices:
                words.extend(str(choice) for choice in action.choices)
        suggestions.append(f"        {shlex.quote(state)}) words={shlex.quote(' '.join(words))} ;;")

    visit(parser, "root")
    values = "|".join(shlex.quote(option) for option in sorted(value_options))
    return "\n".join(
        [
            "# Bash completion for labctl; generated by labctl completion bash.",
            "# Source this file, or install it as /etc/bash_completion.d/labctl.",
            "_labctl_complete() {",
            '    local cur="${COMP_WORDS[COMP_CWORD]}" state=root word words candidate',
            "    local i skip=0",
            "    COMPREPLY=()",
            "    for ((i=1; i<COMP_CWORD; i++)); do",
            '        word="${COMP_WORDS[i]}"',
            "        if ((skip)); then skip=0; continue; fi",
            '        case "$word" in',
            "            --) return 0 ;;",
            f"            {values}) skip=1; continue ;;",
            "            -*) continue ;;",
            "        esac",
            '        case "$state:$word" in',
            *transitions,
            "        esac",
            "    done",
            "    if ((skip)); then return 0; fi",
            '    case "$state" in',
            *suggestions,
            "    esac",
            "    while IFS= read -r candidate; do",
            '        COMPREPLY+=("$candidate")',
            '    done < <(compgen -W "$words" -- "$cur")',
            "    return 0",
            "}",
            "complete -o bashdefault -o default -F _labctl_complete labctl",
            "",
        ]
    )
